version: "3"

services:
  django:
    build: .
    ports:
      - "8000:8000"
      # (host:container)
    volumes:
      - .:/PopularArticle
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
      #從.env檔中獲取連線資料庫的敏感資訊
